# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='none', max_length=100, verbose_name='option1'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='none', max_length=100, verbose_name='option2'),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='none', max_length=100, verbose_name='option3'),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default='none', max_length=100, verbose_name='option4'),
        ),
    ]
