# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20161028_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(choices=[('yes', 'correct'), ('no', 'incorrect')], default='none', max_length=100, verbose_name='option1'),
        ),
    ]
